export { default as RouterComponent } from './RouterComponent';
export { default as NotFoundPage } from './NotFoundPage';
export { default as Navbar } from './Navbar';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Absences } from './Absences';
export { default as Teachers } from './Teachers';
export { default as Classes } from './Classes';
export { default as SingleClass } from './SingleClass';